import Link from "next/link";
import MemberSignOut from "../../../components/MemberSignOut";
import {requireMember} from "../../../lib/memberAuth";
import {supabaseAdmin} from "../../../lib/supabaseAdmin";
const labels:Record<string,string>={parenting_guidance:"Parenting guidance",education_learning:"Education & learning support",family_routines:"Family routines & organisation",faith_family:"Faith & family encouragement",community_resources:"Community resources",emotional_encouragement:"Encouragement for a parent",early_childhood:"Early childhood",primary_years:"Primary years",teen_years:"Teen years",young_adult_transition:"Young-adult transition",information_resources:"Information & resources",one_to_one_adult_guidance:"One-to-one adult guidance",parent_groups:"Parent group support",workshops:"Workshops / learning sessions",community_referral:"Referral to a community resource",weekday_mornings:"Weekday mornings",weekday_afternoons:"Weekday afternoons",weekday_evenings:"Weekday evenings",weekends:"Weekends",flexible:"Flexible",planning:"Planning ahead",soon:"Helpful soon",prompt:"Prompt response appreciated"};
function list(v:string[]|null){return(v||[]).map(x=>labels[x]||x).join(", ")||"Not specified";}export const dynamic="force-dynamic";
export default async function OpportunitiesPage(){const {user}=await requireMember("community_partner");const {data:profile}=await supabaseAdmin.from("community_partner_profiles").select("verification_status,support_areas,support_formats,availability").eq("user_id",user.id).maybeSingle();if(profile?.verification_status!=="verified")return <main className="pledge-page"><section className="pledge-card"><h1>Support Opportunities</h1><p>Community Partner verification is required before support opportunities can be viewed.</p><Link className="button primary" href="/community-partner/onboarding">Return Home</Link></section></main>;
const {data:requests}=await supabaseAdmin.from("parent_support_requests").select("id,support_areas,family_stage,preferred_support,availability,urgency,created_at").eq("status","open").order("created_at",{ascending:false}).limit(50);const partnerAreas=new Set(profile.support_areas||[]);const partnerFormats=new Set(profile.support_formats||[]);const partnerAvailability=new Set(profile.availability||[]);const ranked=(requests||[]).map(r=>{let score=0;if((r.support_areas||[]).some((x:string)=>partnerAreas.has(x)))score+=3;if((r.preferred_support||[]).some((x:string)=>partnerFormats.has(x)))score+=2;if((r.availability||[]).some((x:string)=>partnerAvailability.has(x)))score+=1;return {...r,score};}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score||new Date(b.created_at).getTime()-new Date(a.created_at).getTime());
return <main className="pledge-page"><section className="pledge-hero" style={{textAlign:"center"}}><p className="eyebrow">#RaiseThemRight Community</p><h1>Parent Support Opportunities</h1><p>Broad, privacy-safe requests that may fit the support you offer.</p></section><section className="pledge-card"><div style={{display:"flex",justifyContent:"space-between",gap:"1rem",flexWrap:"wrap",alignItems:"center"}}><Link href="/community-partner/onboarding" style={{fontWeight:700}}>← Community Partner Home</Link><MemberSignOut/></div><div role="note" style={{margin:"1.25rem 0",padding:"1rem",border:"1px solid #f2b632",borderLeft:"5px solid #f2b632",background:"#fff8e7",borderRadius:"12px"}}><strong>Privacy comes before matching.</strong><p style={{margin:".35rem 0 0"}}>These opportunities show broad family needs only. Parent contact information and child-identifying details are not disclosed. This first view is read-only while the protected connection workflow is being certified.</p></div>{!ranked.length?<div style={{padding:"1.25rem",border:"1px solid #ddd",borderRadius:"14px"}}><h2>No suitable open opportunities right now</h2><p>New privacy-safe requests that overlap with your support profile will appear here.</p></div>:<div style={{display:"grid",gap:"1rem"}}>{ranked.map((r,i)=><article key={r.id} style={{padding:"1.15rem",border:"1px solid #ddd",borderRadius:"14px",background:"#fffdf7"}}><p className="eyebrow">SUPPORT OPPORTUNITY {i+1}</p><h2 style={{margin:".2rem 0 .8rem"}}>{list(r.support_areas)}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:".8rem"}}><div><strong>Broad family stage</strong><p>{list(r.family_stage)}</p></div><div><strong>Preferred support</strong><p>{list(r.preferred_support)}</p></div><div><strong>General availability</strong><p>{list(r.availability)}</p></div><div><strong>Timing</strong><p>{labels[r.urgency]||r.urgency||"Not specified"}</p></div></div><div style={{marginTop:".65rem",fontSize:".88rem",color:"#667085"}}>Potential profile fit: {r.score>=5?"Strong":r.score>=3?"Good":"Possible"}</div></article>)}</div>}</section></main>}
