"use client";
import { FormEvent, useState } from "react";
import MemberSignOut from "../../../components/MemberSignOut";

const groups = {
 supportAreas:{title:"What kind of support are you looking for?",options:[["parenting_guidance","Parenting guidance"],["education_learning","Education & learning support"],["family_routines","Family routines & organisation"],["positive_discipline","Positive discipline"],["faith_family","Faith & family encouragement"],["community_resources","Community resources"],["emotional_encouragement","Encouragement for me as a parent"]]},
 familyStage:{title:"Which broad family stage is relevant?",options:[["early_childhood","Early childhood"],["primary_years","Primary years"],["teen_years","Teen years"],["young_adult_transition","Young-adult transition"]]},
 preferredSupport:{title:"What kind of support would you prefer?",options:[["information_resources","Information & resources"],["one_to_one_guidance","One-to-one adult guidance"],["group_support","Parent group support"],["workshops","Workshops / learning sessions"],["community_referral","Referral to a community resource"]]},
 availability:{title:"When are you generally available?",options:[["weekday_mornings","Weekday mornings"],["weekday_afternoons","Weekday afternoons"],["weekday_evenings","Weekday evenings"],["weekends","Weekends"],["flexible","Flexible"]]}
} as const;
type Group=keyof typeof groups; type State=Record<Group,string[]>;
const empty:State={supportAreas:[],familyStage:[],preferredSupport:[],availability:[]};
export default function SupportRequestClient(){
 const [values,setValues]=useState<State>(empty); const [urgency,setUrgency]=useState("planning"); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 function toggle(group:Group,value:string){setValues(current=>({...current,[group]:current[group].includes(value)?current[group].filter(v=>v!==value):[...current[group],value]}));}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");const response=await fetch("/api/parent/support-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,urgency})});const result=await response.json();setSaving(false);if(!response.ok){setError(result.error||"Unable to create support request.");return;}setMessage(result.message);setValues(empty);setUrgency("planning");}
 return <main className="pledge-page"><section className="pledge-hero" style={{textAlign:"center"}}><p className="eyebrow">#RaiseThemRight Community</p><h1>Request Support</h1><p>Tell us what kind of adult-to-adult support may be helpful. No child's identity is needed.</p></section><section className="pledge-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem",marginBottom:"1rem"}}><a href="/parent/onboarding" style={{fontWeight:700,color:"#0b1d3a"}}>← Parent Home</a><MemberSignOut /></div><div role="note" style={{padding:"1.15rem 1.25rem",borderRadius:"12px",background:"#fff8e7",border:"1px solid #f2b632",borderLeft:"5px solid #f2b632",marginBottom:"1.5rem",color:"#13213a"}}><strong style={{display:"block",fontSize:"1.05rem"}}>A quick privacy reminder</strong><p style={{margin:"0.4rem 0 0",lineHeight:1.5}}>Please describe the need only through the broad choices below. Do not provide a child's name, photograph, school, exact age, address, telephone number, or personal story. This request is about support for you as the parent or family adult.</p></div><form className="pledge-form" onSubmit={submit}>{(Object.entries(groups) as [Group,(typeof groups)[Group]][]).map(([name,group])=><fieldset key={name} style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{padding:"0 0.4rem",fontWeight:700}}>{group.title}</legend><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(230px, 1fr))",gap:"0.75rem 1.25rem"}}>{group.options.map(([value,label])=><label key={value} style={{display:"flex",gap:"0.55rem"}}><input type="checkbox" checked={values[name].includes(value)} onChange={()=>toggle(name,value)} style={{width:"auto"}}/><span>{label}</span></label>)}</div></fieldset>)}<fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{padding:"0 0.4rem",fontWeight:700}}>When would support be most useful?</legend><div style={{display:"grid",gap:"0.65rem"}}>{[["planning","I am planning ahead"],["soon","Support would be helpful soon"],["prompt","I would appreciate a prompt response"]].map(([value,label])=><label key={value} style={{display:"flex",gap:"0.55rem"}}><input type="radio" name="urgency" value={value} checked={urgency===value} onChange={()=>setUrgency(value)} style={{width:"auto"}}/><span>{label}</span></label>)}</div></fieldset>{error&&<p className="form-error">{error}</p>}{message&&<div role="status" style={{width:"100%",padding:"1rem",borderRadius:"12px",background:"#eef5ff",border:"1px solid #9fc3ef",color:"#0b3a70"}}><strong>Request Created ✓</strong><p style={{margin:"0.35rem 0 0"}}>{message}</p></div>}<button type="submit" className="button primary" disabled={saving}>{saving?"Creating request...":"Create Support Request"}</button></form></section></main>;
}
