"use client";
import {FormEvent,useEffect,useState} from "react";
import MemberSignOut from "../../../components/MemberSignOut";
const certifiers=[["justice_of_peace","Justice of the Peace"],["attorney_notary","Attorney-at-Law / Notary Public"],["medical_doctor","Medical Doctor"],["gazetted_police_officer","Gazetted Police Officer"],["school_principal","School / Tertiary Institution Principal"],["bank_credit_union_manager","Bank / Credit Union Manager"],["marriage_officer_minister","Marriage Officer / Authorised Minister of Religion"],["clerk_of_courts","Clerk of Courts"],["senior_public_officer","Senior Public Officer"],["jamaican_consular_officer","Jamaican Consular Officer"]] as const;
type Doc={document_type:string;original_filename:string;uploaded_at:string};
const fieldLabel={display:"grid",gap:".35rem",fontWeight:600} as const;
const helper={margin:".25rem 0 0",fontSize:".9rem",lineHeight:1.45,color:"#5f6b7a"} as const;
const section={width:"100%",border:"1px solid #d9d9d9",borderRadius:"14px",padding:"1.2rem",display:"grid",gap:"1.05rem"} as const;
const legend={fontWeight:800,padding:"0 .45rem",color:"#c88900",fontSize:".9rem",letterSpacing:".09em",textTransform:"uppercase" as const};
export default function VerificationClient({status,currentStandard}:{status:string;currentStandard:boolean}){
 const [current,setCurrent]=useState(status);const [documents,setDocuments]=useState<Doc[]>([]);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
 const [form,setForm]=useState({role:"",affiliation:"",certifierType:"",certifierName:"",certifiedDate:"",referenceName:"",referenceContact:"",referenceRelationship:"",referenceLetterDate:"",credentials:"",safeguardingAgreed:false});
 const needsUpgrade=current==="verified"&&!currentStandard;
 useEffect(()=>{fetch("/api/community-partner/verification/evidence").then(r=>r.json()).then(v=>setDocuments(v.documents||[])).catch(()=>undefined);},[]);
 function change(name:string,value:string|boolean){setForm(v=>({...v,[name]:value}));}
 async function upload(documentType:string,file:File|null){if(!file)return;setUploading(documentType);setError("");setMessage("");const data=new FormData();data.append("documentType",documentType);data.append("file",file);const r=await fetch("/api/community-partner/verification/evidence",{method:"POST",body:data});const result=await r.json();setUploading("");if(!r.ok){setError(result.error||"Unable to upload verification evidence.");return;}setMessage(result.message);const refreshed=await fetch("/api/community-partner/verification/evidence").then(x=>x.json());setDocuments(refreshed.documents||[]);}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");const r=await fetch("/api/community-partner/verification",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await r.json();setSaving(false);if(!r.ok){setError(result.error||"Unable to submit verification application.");return;}setCurrent("pending");setMessage(result.message);}
 const hasId=documents.some(d=>d.document_type==="certified_id"),hasPhoto=documents.some(d=>d.document_type==="verification_photo"),hasReference=documents.some(d=>d.document_type==="reference_letter");const showForm=current==="not_started"||current==="declined"||needsUpgrade;
 return <main className="pledge-page"><section className="pledge-hero" style={{textAlign:"center"}}><p className="eyebrow">#RaiseThemRight Community</p><h1>Community Partner Verification</h1><p>Build trust through identity evidence, safeguarding and adult references.</p></section><section className="pledge-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem",flexWrap:"wrap",marginBottom:"1rem"}}><a href="/community-partner/onboarding" style={{fontWeight:700,color:"#0b1d3a"}}>← Community Partner Home</a><MemberSignOut/></div>
 <div role="note" style={{padding:"1rem 1.15rem",borderRadius:"12px",background:"#fff8e7",border:"1px solid #f2b632",borderLeft:"5px solid #f2b632",marginBottom:"1.5rem",color:"#13213a"}}><strong>Your evidence stays private</strong><p style={helper}>Certified ID, verification photo and reference letter are used only for verification. They are not automatically shared with other members.</p></div>
 {current==="pending"&&<div style={{padding:"1.25rem",border:"1px solid #9fc3ef",background:"#eef5ff",borderRadius:"14px"}}><h2>Pending review</h2><p>Your strengthened verification application is with Mission Control. Support opportunities remain unavailable until the review is completed.</p></div>}
 {current==="verified"&&!showForm&&<div style={{padding:"1.25rem",border:"1px solid #9fc3ef",background:"#eef5ff",borderRadius:"14px"}}><h2>Verified</h2><p>Your Community Partner account is verified under the current verification standard.</p></div>}
 {showForm&&<form className="pledge-form" onSubmit={submit} style={{gap:"1.5rem"}}>
 {needsUpgrade&&<div style={{width:"100%",padding:"1rem",borderRadius:"12px",background:"#eef5ff",border:"1px solid #9fc3ef",color:"#0b3a70"}}><strong>Verification upgrade required</strong><p style={{...helper,color:"#0b3a70"}}>Complete this application so your earlier approval can be reviewed under the strengthened safeguards.</p></div>}
 <fieldset style={section}><legend style={legend}>Adult role & background *</legend><label style={fieldLabel}>Role or capacity<input value={form.role} onChange={e=>change("role",e.target.value)} placeholder="e.g. Teacher, counsellor, pastor, mentor, experienced parent" required/></label><label style={fieldLabel}>Organisation or affiliation <span style={{fontWeight:400}}>(optional)</span><input value={form.affiliation} onChange={e=>change("affiliation",e.target.value)} placeholder="Organisation, church, school, community group, etc."/></label><label style={fieldLabel}>Relevant qualifications / credentials <span style={{fontWeight:400}}>(optional)</span><textarea value={form.credentials} onChange={e=>change("credentials",e.target.value)} rows={3} style={{width:"100%",minHeight:"90px",resize:"vertical"}} placeholder="Credentials or experience Mission Control may need to verify."/></label></fieldset>
 <fieldset style={section}><legend style={legend}>Certified identification *</legend><div><strong>Upload a certified copy of your valid ID</strong><p style={helper}>Do not upload the original document. The copy must be certified within the last <strong>6 months</strong>.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:"1rem"}}><label style={fieldLabel}>Accepted certifier<select value={form.certifierType} onChange={e=>change("certifierType",e.target.value)} required><option value="">Choose certifier</option>{certifiers.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={fieldLabel}>Certifier's name<input value={form.certifierName} onChange={e=>change("certifierName",e.target.value)} placeholder="Full name of certifier" required/></label></div><label style={fieldLabel}>Date certified<input type="date" value={form.certifiedDate} onChange={e=>change("certifiedDate",e.target.value)} required/></label><div style={{padding:".9rem 1rem",borderRadius:"12px",background:"#f7f4eb"}}><strong>{hasId?"Certified ID uploaded ✓":"Choose certified ID file"}</strong><p style={helper}>JPG, PNG or PDF • Maximum 10 MB • Signed and dated certification with appropriate stamp, seal or identifying information.</p><input style={{marginTop:".65rem"}} type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>upload("certified_id",e.target.files?.[0]||null)} disabled={uploading==="certified_id"}/></div></fieldset>
 <fieldset style={section}><legend style={legend}>Private verification photo *</legend><div><strong>Upload a recent photo of yourself</strong><p style={helper}>For Mission Control identity comparison only. It is not automatically shared as your profile photo.</p></div><div style={{padding:".9rem 1rem",borderRadius:"12px",background:"#f7f4eb"}}><strong>{hasPhoto?"Verification photo uploaded ✓":"Choose verification photo"}</strong><p style={helper}>JPG or PNG • Maximum 10 MB.</p><input style={{marginTop:".65rem"}} type="file" accept="image/jpeg,image/png" onChange={e=>upload("verification_photo",e.target.files?.[0]||null)} disabled={uploading==="verification_photo"}/></div></fieldset>
 <fieldset style={section}><legend style={legend}>Adult reference *</legend><div><strong>Provide an independent adult reference</strong><p style={helper}>The referee must not be an immediate family member. Mission Control may contact the referee independently.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:"1rem"}}><label style={fieldLabel}>Reference name<input value={form.referenceName} onChange={e=>change("referenceName",e.target.value)} required/></label><label style={fieldLabel}>Relationship / capacity<input value={form.referenceRelationship} onChange={e=>change("referenceRelationship",e.target.value)} placeholder="e.g. Employer, pastor, colleague, community leader" required/></label></div><label style={fieldLabel}>Reference contact information<input value={form.referenceContact} onChange={e=>change("referenceContact",e.target.value)} placeholder="Telephone or email" required/></label><label style={fieldLabel}>Date of reference letter<input type="date" value={form.referenceLetterDate} onChange={e=>change("referenceLetterDate",e.target.value)} required/></label><div style={{padding:".9rem 1rem",borderRadius:"12px",background:"#f7f4eb"}}><strong>{hasReference?"Reference letter uploaded ✓":"Choose reference letter"}</strong><p style={helper}>Signed and dated within the last 6 months • JPG, PNG or PDF • Maximum 10 MB. The letter is private verification evidence.</p><input style={{marginTop:".65rem"}} type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>upload("reference_letter",e.target.files?.[0]||null)} disabled={uploading==="reference_letter"}/></div></fieldset>
 <fieldset style={section}><legend style={legend}>Safeguarding declaration *</legend><div><strong>I agree to support adults and families safely.</strong><p style={helper}>By checking the box, I agree that I will:</p><div style={{display:"grid",gap:".3rem",marginTop:".55rem",fontSize:".92rem",lineHeight:1.4,color:"#344054"}}><span>• Not independently contact children or request unnecessary child-identifying information.</span><span>• Follow #RaiseThemRight safety rules and appropriate connection boundaries.</span><span>• Not use a connection to solicit money, private information or inappropriate contact.</span><span>• Respect confidentiality and the safety requirements of each connection.</span></div></div><label style={{display:"flex",gap:".7rem",alignItems:"flex-start",fontWeight:600}}><input type="checkbox" checked={form.safeguardingAgreed} onChange={e=>change("safeguardingAgreed",e.target.checked)} style={{width:"auto",marginTop:".25rem"}}/><span>I have read and agree to the safeguarding declaration.</span></label></fieldset>
 {error&&<p className="form-error">{error}</p>}{message&&<div role="status" style={{width:"100%",padding:"1rem",borderRadius:"12px",background:"#eef5ff",border:"1px solid #9fc3ef",color:"#0b3a70"}}><strong>Saved ✓</strong><p style={{margin:".35rem 0 0"}}>{message}</p></div>}
 <button type="submit" className="button primary" disabled={saving||uploading!==""}>{saving?"Submitting for review...":"Submit Verification Application"}</button>
 </form>}
 </section></main>;
}
