"use client";
import {FormEvent,useEffect,useState} from "react";
import MemberSignOut from "../../../components/MemberSignOut";

const certifiers=[
 ["justice_of_peace","Justice of the Peace"],
 ["attorney_notary","Attorney-at-Law / Notary Public"],
 ["medical_doctor","Medical Doctor"],
 ["gazetted_police_officer","Gazetted Police Officer"],
 ["school_principal","School / Tertiary Institution Principal"],
 ["bank_credit_union_manager","Bank / Credit Union Manager"],
 ["marriage_officer_minister","Marriage Officer / Authorised Minister of Religion"],
 ["clerk_of_courts","Clerk of Courts"],
 ["senior_public_officer","Senior Public Officer"],
 ["jamaican_consular_officer","Jamaican Consular Officer"]
] as const;

type Doc={document_type:string;original_filename:string;uploaded_at:string};
export default function VerificationClient({status}:{status:string}){
 const [current,setCurrent]=useState(status);const [documents,setDocuments]=useState<Doc[]>([]);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
 const [form,setForm]=useState({role:"",affiliation:"",certifierType:"",certifierName:"",certifiedDate:"",referenceName:"",referenceContact:"",credentials:"",safeguardingAgreed:false});
 const needsUpgrade=current==="verified";
 useEffect(()=>{fetch("/api/community-partner/verification/evidence").then(r=>r.json()).then(v=>setDocuments(v.documents||[])).catch(()=>undefined);},[]);
 function change(name:string,value:string|boolean){setForm(v=>({...v,[name]:value}));}
 async function upload(documentType:string,file:File|null){if(!file)return;setUploading(documentType);setError("");setMessage("");const data=new FormData();data.append("documentType",documentType);data.append("file",file);const r=await fetch("/api/community-partner/verification/evidence",{method:"POST",body:data});const result=await r.json();setUploading("");if(!r.ok){setError(result.error||"Unable to upload verification evidence.");return;}setMessage(result.message);const refreshed=await fetch("/api/community-partner/verification/evidence").then(x=>x.json());setDocuments(refreshed.documents||[]);}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");const r=await fetch("/api/community-partner/verification",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await r.json();setSaving(false);if(!r.ok){setError(result.error||"Unable to submit verification application.");return;}setCurrent("pending");setMessage(result.message);}
 const hasId=documents.some(d=>d.document_type==="certified_id");const hasPhoto=documents.some(d=>d.document_type==="verification_photo");
 const showForm=current==="not_started"||current==="declined"||needsUpgrade;
 return <main className="pledge-page"><section className="pledge-hero" style={{textAlign:"center"}}><p className="eyebrow">#RaiseThemRight Community</p><h1>Community Partner Verification</h1><p>Build trust through identity evidence, safeguarding and adult references.</p></section><section className="pledge-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem",flexWrap:"wrap",marginBottom:"1rem"}}><a href="/community-partner/onboarding" style={{fontWeight:700,color:"#0b1d3a"}}>← Community Partner Home</a><MemberSignOut/></div>
 <div role="note" style={{padding:"1.15rem 1.25rem",borderRadius:"12px",background:"#fff8e7",border:"1px solid #f2b632",borderLeft:"5px solid #f2b632",marginBottom:"1.5rem",color:"#13213a"}}><strong style={{display:"block",fontSize:"1.05rem"}}>Your evidence stays private</strong><p style={{margin:".4rem 0 0"}}>Certified ID and the private verification photo are reviewed only for verification. They are not public profile images and are not shared with Parents or other Community Partners.</p></div>
 {current==="pending"&&<div style={{padding:"1.25rem",border:"1px solid #9fc3ef",background:"#eef5ff",borderRadius:"14px"}}><h2>Pending review</h2><p>Your strengthened verification application is with Mission Control. Support opportunities remain unavailable until the review is completed.</p></div>}
 {current==="verified"&&!showForm&&<div style={{padding:"1.25rem",border:"1px solid #9fc3ef",background:"#eef5ff",borderRadius:"14px"}}><h2>Verified</h2><p>Your Community Partner account is verified under the current verification standard.</p></div>}
 {showForm&&<form className="pledge-form" onSubmit={submit}>
  {needsUpgrade&&<div style={{width:"100%",padding:"1rem",borderRadius:"12px",background:"#eef5ff",border:"1px solid #9fc3ef",color:"#0b3a70"}}><strong>Verification upgrade required</strong><p style={{margin:".35rem 0 0"}}>Your earlier approval occurred before the strengthened evidence standard. Complete this application so your verification can be reviewed under the new safeguards.</p></div>}
  <fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{fontWeight:700}}>Your adult role and background *</legend><label>Role or capacity<input value={form.role} onChange={e=>change("role",e.target.value)} placeholder="e.g. Teacher, counsellor, pastor, mentor, experienced parent" required/></label><label>Organisation or affiliation <span style={{fontWeight:400}}>(optional)</span><input value={form.affiliation} onChange={e=>change("affiliation",e.target.value)} placeholder="Organisation, church, school, community group, etc."/></label><label>Relevant qualifications / credentials <span style={{fontWeight:400}}>(optional where not applicable)</span><textarea value={form.credentials} onChange={e=>change("credentials",e.target.value)} rows={3} placeholder="Briefly state credentials or professional experience that Mission Control may need to verify."/></label></fieldset>
  <fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{fontWeight:700}}>Certified identification *</legend><p style={{marginTop:0}}>The copy must be certified within the last <strong>6 months</strong>. The ID itself must still be valid.</p><label>Accepted certifier<select value={form.certifierType} onChange={e=>change("certifierType",e.target.value)} required><option value="">Choose certifier</option>{certifiers.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Certifier's name<input value={form.certifierName} onChange={e=>change("certifierName",e.target.value)} required/></label><label>Date certified<input type="date" value={form.certifiedDate} onChange={e=>change("certifiedDate",e.target.value)} required/></label><div style={{padding:"1rem",borderRadius:"12px",background:"#f7f4eb"}}><strong>{hasId?"Certified ID uploaded ✓":"Upload certified ID"}</strong><p style={{margin:".35rem 0 .7rem"}}>JPG, PNG or PDF, maximum 10 MB. The certification should be signed, dated and carry the certifier's appropriate stamp, seal or identifying information.</p><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>upload("certified_id",e.target.files?.[0]||null)} disabled={uploading==="certified_id"}/>{uploading==="certified_id"&&<p>Uploading securely...</p>}</div></fieldset>
  <fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{fontWeight:700}}>Private verification photo *</legend><p style={{marginTop:0}}>Upload a clear, recent photograph of <strong>you, the adult account holder</strong>. This is for Mission Control identity comparison and is not automatically shared as your profile photo.</p><div style={{padding:"1rem",borderRadius:"12px",background:"#f7f4eb"}}><strong>{hasPhoto?"Verification photo uploaded ✓":"Upload private verification photo"}</strong><p style={{margin:".35rem 0 .7rem"}}>JPG or PNG, maximum 10 MB.</p><input type="file" accept="image/jpeg,image/png" onChange={e=>upload("verification_photo",e.target.files?.[0]||null)} disabled={uploading==="verification_photo"}/>{uploading==="verification_photo"&&<p>Uploading securely...</p>}</div></fieldset>
  <fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{fontWeight:700}}>Adult reference *</legend><p style={{marginTop:0}}>Provide a responsible adult whom Mission Control may contact as part of verification.</p><label>Reference name<input value={form.referenceName} onChange={e=>change("referenceName",e.target.value)} required/></label><label>Reference contact information<input value={form.referenceContact} onChange={e=>change("referenceContact",e.target.value)} placeholder="Telephone or email" required/></label></fieldset>
  <fieldset style={{width:"100%",border:"1px solid #d9d9d9",borderRadius:"12px",padding:"1rem"}}><legend style={{fontWeight:700}}>Safeguarding declaration *</legend><label style={{display:"flex",gap:".7rem",alignItems:"flex-start"}}><input type="checkbox" checked={form.safeguardingAgreed} onChange={e=>change("safeguardingAgreed",e.target.checked)} style={{width:"auto",marginTop:".25rem"}}/><span>I understand that #RaiseThemRight is an adult-to-adult support community. I will not independently contact children, request unnecessary child-identifying information, bypass platform safety rules, or use a connection to solicit money, private information or inappropriate contact. I agree to respect confidentiality, boundaries and the safety requirements of each connection.</span></label></fieldset>
  {error&&<p className="form-error">{error}</p>}{message&&<div role="status" style={{width:"100%",padding:"1rem",borderRadius:"12px",background:"#eef5ff",border:"1px solid #9fc3ef",color:"#0b3a70"}}><strong>Saved ✓</strong><p style={{margin:".35rem 0 0"}}>{message}</p></div>}
  <button type="submit" className="button primary" disabled={saving||uploading!==""}>{saving?"Submitting for review...":"Submit Verification Application"}</button>
 </form>}
 </section></main>;
}
